WorxLandroid Binding Readme.md - First step
clinique/openhab2-addons pull request #24
Opened 2024-06-21 18:09 UTC by sihui62

see also PM in community forum

2024-06-24 07:27 UTC, clinique requested changes
Thanks for your complete review of the documentation. Some minor observations.

2024-06-24 07:27 UTC, clinique commented on bundles/org.openhab.binding.worxlandroid/README.md
> +| status           | `String`   | common#status           | *1 (see below)    |
Please, remove the "`" backticks

2024-06-24 07:27 UTC, clinique commented on bundles/org.openhab.binding.worxlandroid/README.md
> +| timestamp | `DateTime` | config#timestamp |
Same here

2024-06-24 07:27 UTC, clinique commented on bundles/org.openhab.binding.worxlandroid/README.md
> +| enable   | `Switch`      | sunday#enable   |
Here also

2024-06-24 11:47 UTC, sihui62 commented
> Please, remove the "`" backticks

done.

2024-07-08 07:10 UTC, clinique approved these changes

2024-07-08 07:10 UTC, merged