Netatmo oh3 update
clinique/openhab2-addons pull request #3
Opened 2021-05-11 12:37 UTC by wzbfyb

2021-05-11 13:01 UTC, clinique requested changes
First draft review. Once you'll have reactivate sat tests, you'll find many things to address. Thanks for your work.

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHome.java
> +    private @Nullable NAObjectMap<NARoom> rooms;
I would prefer having this non null with an empty list like the other above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHome.java
> +    public void setRooms(NAObjectMap<NARoom> rooms) {
Is this of any use somewhere ?

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHome.java
> +        return rooms.get(key);
Subject to NPE if rooms is null

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHomeStatus.java
> + * @author Gaël L'hopital - Initial contribution
Change author to yourself. You did it, be proud of it.

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> + * @author Gaël L'hopital - Initial contribution
Same than above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    private int heating_power_request;
should be heatingPowerRequest

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    private boolean open_window;
should be openWindow

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    private Double therm_measured_temperature;
same as above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    private String therm_setpoint_mode;
same as above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    private Double therm_setpoint_temperature;
same as above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public int getHeating_power_request() {
this method should be getHeatingPowerRequest()

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public void setHeating_power_request(int heating_power_request) {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public boolean isOpen_window() {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public void setOpen_window(boolean open_window) {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public Double getTherm_measured_temperature() {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public void setTherm_measured_temperature(Double therm_measured_temperature) {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public String getTherm_setpoint_mode() {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public void setTherm_setpoint_mode(String therm_setpoint_mode) {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public double getTherm_setpoint_temperature() {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NARoom.java
> +    public void setTherm_setpoint_temperature(Double therm_setpoint_temperature) {
see above

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Body.java
> +    private Map<String, Object> additionalProperties = new HashMap<String, Object>();
`private Map<String, Object> additionalProperties = new HashMap<>();`

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Body.java
> +    public Body() {
Not sure this is really needed

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Home.java
> +    public Home() {
Not sure this is really needed

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/pom.xml
> +  <properties>
You should not skip stat tests

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Home.java
> +    private Map<String, Object> additionalProperties = new HashMap<String, Object>();
`private Map<String, Object> additionalProperties = new HashMap<>();`

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Home.java
> +    private List<Module> modules = new ArrayList<Module>();
`private List<Module> modules = new ArrayList<>();`

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Home.java
> +    private List<Room> rooms = new ArrayList<Room>();
`private List<Room> rooms = new ArrayList<>();`

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Homestatus.java
> +    private Integer timeServer;
Use primitive type instead

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Homestatus.java
> +    private Map<String, Object> additionalProperties = new HashMap<String, Object>();
Use diamond operator

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Module.java
> +    private Integer firmwareRevision;
use primitive types when possible

2021-05-11 13:01 UTC, clinique commented on bundles/org.openhab.binding.netatmo/wie_builden.txt
> +mvn clean install -DskipChecks -pl :org.openhab.binding.netatmo
This should not stay in the repo

2021-05-28 15:57 UTC, wzbfyb commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHome.java
> +    public void setRooms(NAObjectMap<NARoom> rooms) {
not anymore, removed it

2021-05-28 16:00 UTC, wzbfyb commented on bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/energy/Homestatus.java
> +    private Integer timeServer;
thanks, most of the classes I am editing now where actually from a code generator :)

2021-06-02 09:54 UTC, closed without merging